---
- hosts: haproxy
  name: HAProxy Instance Configuration
  
  roles:
    - firewalld

  tasks:
  
  - name: hostname
    shell: >
      hostnamectl set-hostname haproxy.{{ hostvars['openstack']['openshift_domain'] }}
  
  - name: epel-release
    yum:
      name: "epel-release"
      state: present

  - name: install packages
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - haproxy
