---
- hosts: osp
  name: Create DNS Security Group

  tasks:

    - name: create icmp and 22/tcp rules
      shell: >
        source ~/keystonerc_admin && export OS_PROJECT_NAME=lab && \
        openstack security group rule create \
          --ingress \
          --protocol icmp \
          dns-sg && \
        openstack security group rule create \
          --ingress \
          --protocol tcp \
          --dst-port 22 \
          dns-sg
            
    - name: create rule for port 53/tcp and 53/udp
      shell: >
        source ~/keystonerc_admin && export OS_PROJECT_NAME=lab && \
        openstack security group rule create \
          --ingress \
          --protocol {{ item }} \
          --dst-port 53 \
          dns-sg
      with_items:
        - udp
        - tcp
