---
- hosts: osp
  name: Create HAPRoxy Security Group

  tasks:

    - name: create icmp rule
      shell: >
        source ~/keystonerc_admin && export OS_PROJECT_NAME=lab && \
        openstack security group rule create \
          --ingress \
          --protocol icmp \
          haproxy-sg
            
    - name: create rules for ports 22/tcp, 80/tcp, 443/tcp, 8443/tcp and 9000/tcp ports
      shell: >
        source ~/keystonerc_admin && export OS_PROJECT_NAME=lab && \
        openstack security group rule create \
          --ingress \
          --protocol tcp \
          --dst-port {{ item }} \
          haproxy-sg
      with_items:
        - 22
        - 80
        - 443
        - 8443
        - 9000
