---
- name: remove default repositories
  file:
    path: "/etc/yum.repos.d/"
    state: absent

- name: copy nexus repository file
  copy:
    src: "nexus.repo"
    dest: "/etc/yum.repos.d/"

- name: copy gpg files
  copy:
    src: "rpm-gpg/"
    dest: "/etc/pki/rpm-gpg/"

- name: add nexus-server ip to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ servers.nexus.name }}"
    line: "{{ servers.nexus.ip_address }} {{ servers.nexus.name }}"
