# put nexus tar file and oracle java rpm on install folder before execute this playbook
all:
  hosts:
    nexus:
      ansible_host: 192.168.1.114
      ansible_user: root

  vars:
    java_install: "jdk-8u172-linux-x64.rpm"
    nexus_version: "3.11.0-01"
    nexus_install: "nexus-{{ nexus_version }}-unix.tar.gz"
    
    # created with:
    # python -c 'import crypt; print crypt.crypt("This is my Password", "$1$SomeSalt$")'
    nexus_password: $1$SomeSalt$UqddPX3r4kH3UL5jq5/ZI.
    
    nexus:
      files:
        - "{{ java_install }}"
        - "{{ nexus_install }}"
