---
- hosts: osp
  remote_user: root
  name: Configure OpenStack Images
  
  tasks:

    - name: create images
      shell: >
        source ~/keystonerc_admin && \
        openstack image create \
          --public \
          --disk-format {{ item.value.disk_format }} \
          --min-disk {{ item.value.min_disk }} \
          --min-ram {{ item.value.min_ram }} \
          --file "{{ osp.resource_path }}/{{ item.value.file_name }}" \
          {{ item.key }}
      with_dict: "{{ osp.images }}"

