---
- import_playbook: servers/dns/security-group-creation.yml
- import_playbook: servers/creation.yml
- import_playbook: servers/prepare.yml
- import_playbook: servers/dns/configuration.yml
- import_playbook: servers/dns/network-configuration.yml
- import_playbook: servers/reboot.yml
