---
- hosts: osp
  name: Create DNS Server

  tasks:

    - name: create security group for dns with icmp/ssh rules
      shell: >
        source ~/keystonerc_admin && export OS_PROJECT_NAME=lab && \
        openstack security group create {{ item.value.security_group }} && \
        openstack security group rule create \
          --ingress \
          --protocol icmp \
          {{ item.value.security_group }} && \
        openstack security group rule create \
          --ingress \
          --protocol tcp \
          --dst-port 22 \
          {{ item.value.security_group }}
      with_dict: "{{ osp.lab.servers }}"
      when: item.key == "dns"
            
    - name: create rule for port 53 on tcp/udp protocols
      shell: >
        source ~/keystonerc_admin && export OS_PROJECT_NAME=lab && \
        openstack security group rule create \
          --ingress \
          --protocol {{ item }} \
          --dst-port 53 \
          {{ osp.lab.servers.dns.security_group }}
      with_items:
        - udp
        - tcp
