---
- hosts: osp
  name: Create DNS Security Group (dns-security-group)

  tasks:

    - name: create security group for dns with icmp/ssh rules
      shell: >
        source ~/keystonerc_admin && export OS_PROJECT_NAME=lab && \
        openstack security group create dns-security-group && \
        openstack security group rule create \
          --ingress \
          --protocol icmp \
          dns-security-group && \
        openstack security group rule create \
          --ingress \
          --protocol tcp \
          --dst-port 22 \
          dns-security-group
            
    - name: create rule for port 53 on tcp/udp protocols
      shell: >
        source ~/keystonerc_admin && export OS_PROJECT_NAME=lab && \
        openstack security group rule create \
          --ingress \
          --protocol {{ item }} \
          --dst-port 53 \
          dns-security-group
      with_items:
        - udp
        - tcp
