---
- hosts: openstack
  name: Remove Instances and Subnet Congig Reset

  tasks:

  - name: Set Subnet DNS Server
    shell: >
      openstack subnet set \
        --no-dns-nameservers \
        --dns-nameserver 192.168.1.1 \
        --dns-nameserver 8.8.8.8 \
        lab_subnet

  - name: Delete Servers
    shell: >
      for server in $(openstack server list -c Name -f value);
      do
        openstack server delete $server;
      done;
