---
- import_playbook: config/keypair.yml
- import_playbook: config/network.yml
- import_playbook: config/flavors.yml
- import_playbook: config/images.yml
- import_playbook: config/lab.yml
- import_playbook: config/security-groups.yml
- import_playbook: config/volumes.yml
- import_playbook: config/lab-servers.yml
