osp:
  hosts:
    openstack:
      ansible_connection: local
  vars:
    osp:
      resource_path: /tmp/openstack

      packstack:
        CONFIG_DEFAULT_PASSWORD: openstack
        CONFIG_KEYSTONE_ADMIN_PW: openstack
        CONFIG_CINDER_VOLUMES_SIZE: 300G
        CONFIG_SERVICE_WORKERS: 2
        CONFIG_NTP_SERVERS: pool.ntp.org
        CONFIG_HEAT_INSTALL: y
        CONFIG_PROVISION_DEMO: n
        CONFIG_CEILOMETER_INSTALL: n
        CONFIG_NEUTRON_OVS_BRIDGE_MAPPINGS: physnet1:br-ex

      network:
        nic: eno1
        cidr: 192.168.1.0/24
        dns: 192.168.1.1
        dhcp:
          start: 192.168.1.20
          end: 192.168.1.90

      keypairs:
        server: ~/.ssh/id_rsa.pub

      flavors:
        m1.nano:
          ram: 128
          disk: 1
          ephemeral: 0
          swap: 0
          vcpus: 1
        m1.micro:
          ram: 256
          disk: 1
          ephemeral: 0
          swap: 0
          vcpus: 1

      images:
        cirros:
          file_name: cirros-0.4.0-x86_64-disk.img
          remote_path: http://download.cirros-cloud.net/0.4.0
          disk_format: qcow2
          min_disk: 1
          min_ram: 128

      lab:
        floating_ip:
          - 192.168.1.20
          - 192.168.1.21
          - 192.168.1.22
          - 192.168.1.23
          - 192.168.1.24

        networks:
          workshop:
            cidr: 10.0.0.0/24
            dhcp:
              start: 10.0.0.10
              end: 10.0.0.100

