# Preparation
#
# 1. Configure a Public Network with IP Adresses reserved (you can reserve IP Address based on Mac Address for example). 
#
# This Playbook consider that:
#
# Public Network CIDR created with Cisco Router E900:
#   192.168.1.0/24 {{ network.external.base_ip }}
# 
# Cisco Router E900 (this IP Adress will be the same for base DNS server for Bare Metal Machine)
#   192.168.1.1
# 
# DNS Server IP Reservation
#   192.168.1.2
#
# Nexus Sonatype Repository Manager for Yum Proxy Repository (VM provide by a VirtualBox on my Laptop)
#   192.168.1.3
#
# NTP Server IP Reservation
#   192.168.1.4
#
# HAProxy IP Reservation
#   192.168.1.5
#
# Real Machine for OpenStack installation (Intel NUC Skull Canyon with 32GB of RAM and 1TB SSD Disk)
#   192.168.1.101
# 
# Ansible (My Laptop)
#   192.168.1.125
#
# 2. Install CentOS 7 on NUC
#
all:
  vars:
    servers:
      nexus:
        name: nexus-server
        ip_address: 192.168.1.3
      dns:
        name: DNS Server for Internal Network
        ip_address: 10.0.0.2
        floating_ip: 192.168.1.2
        security_group: dns-sg
      ntp:
        name: NTP Server
        ip_address: 10.0.0.4
        floating_ip: 192.168.1.4
      haproxy:
        name: HAProxy
        ip_address: 10.0.0.5
        floating_ip: 192.168.1.5
        security_group: haproxy-sg
        
    osp:
      resource_path: /tmp/openstack
  
      packstack:
        CONFIG_DEFAULT_PASSWORD: openstack
        CONFIG_KEYSTONE_ADMIN_PW: openstack
        CONFIG_CINDER_VOLUMES_SIZE: 300G
        CONFIG_SERVICE_WORKERS: 2
        CONFIG_NTP_SERVERS: pool.ntp.org
        CONFIG_HEAT_INSTALL: y
        CONFIG_PROVISION_DEMO: n
        CONFIG_CEILOMETER_INSTALL: n
        CONFIG_NEUTRON_OVS_BRIDGE_MAPPINGS: physnet1:br-ex
  
      network:
        nic: eno1
        cidr: 192.168.1.0/24
        dns: 192.168.1.1
        dhcp:
          start: 192.168.1.20
          end: 192.168.1.90
  
      keypairs:
        server: ~/.ssh/id_rsa.pub
  
      flavors:
        m1.nano:
          ram: 128
          disk: 1
          ephemeral: 0
          swap: 0
          vcpus: 1
        m1.micro:
          ram: 256
          disk: 1
          ephemeral: 0
          swap: 0
          vcpus: 1
        ocp.node:
          ram: 4096
          disk: 20
          ephemeral: 0
          swap: 0
          vcpus: 1
        ocp.master:
          ram: 8192
          disk: 15
          ephemeral: 0
          swap: 0
          vcpus: 2
  
      images:
        cirros:
          file_name: cirros-0.4.0-x86_64-disk.img
          remote_path: http://download.cirros-cloud.net/0.4.0
          disk_format: qcow2
          min_disk: 1
          min_ram: 128
        centos:
          file_name: CentOS-7-x86_64-GenericCloud.qcow2
          remote_path: http://cloud.centos.org/centos/7/images
          disk_format: qcow2
          min_disk: 15
          min_ram: 512
  
      lab:
        floating_ip:
          - 192.168.1.2
          - 192.168.1.4
          - 192.168.1.5
          - 192.168.1.31
          - 192.168.1.32
          - 192.168.1.33
          - 192.168.1.34
          - 192.168.1.35
  
        networks:
          lab:
            cidr: 10.0.0.0/24
            dhcp:
              start: 10.0.0.10
              end: 10.0.0.100
        
        security_groups:
          dns: DNS
          bastion: Bastion
          node: Node
          haproxy: HAProxy
          master: Master
          infra: Infrastructure

        servers:
          dns:
            ip_address: "{{ servers.dns.ip_address }}"
            floating_ip: "{{ servers.dns.floating_ip }}"
            network: lab
            flavor: m1.small
            image: centos
            security_group: "{{ servers.dns.security_group }}"
          ntp:
            ip_address: "{{ servers.ntp.ip_address }}"
            floating_ip: "{{ servers.ntp.floating_ip }}"
            network: lab
            flavor: m1.small
            image: centos
            security_group: default
          haproxy:
            ip_address: "{{ servers.haproxy.ip_address }}"
            floating_ip: "{{ servers.haproxy.floating_ip }}"
            network: lab
            flavor: m1.small
            image: centos
            security_group: "{{ servers.haproxy.security_group }}"
          

  children:
    osp:
      hosts:
        openstack:
          ansible_host: 192.168.1.101

    lab:
      vars:
        ansible_user: centos
        ansible_become: yes
      
      hosts:      
        dns:
          ansible_host: "{{ servers.dns.floating_ip }}"
        ntp:
          ansible_host: "{{ servers.ntp.floating_ip }}"
        haproxy:
          ansible_host: "{{ servers.haproxy.floating_ip }}"
