---
- hosts: osp
  name: Prepare OpenStack Installation

  tasks:
  
    - import_tasks: ~/pack-your-lab/nexus/client/configuration.yml

    - name: create resource folder
      file:
        path: "{{ osp.resource_path }}"
        state: directory

    - name: install required packages
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - centos-release-openstack-queens

    - name: update openstack package
      yum:
        name: '*'
        state: latest
        
    - name: install extra packstack packages
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - openstack-packstack
        - openstack-utils
        - python-pip
        - python-openstackclient
        - bash-completion
        - bash-completion-extras

    - name: update packages
      yum:
        name: '*'
        state: latest

    - name: update python pip
      shell: >
        pip install --upgrade pip
        
    - name: configure bash completion for openstack commands
      shell: >
        openstack complete | sudo tee /etc/bash_completion.d/osc.bash_completion > /dev/null

    - name: download images
      get_url:
        url: "{{ item.value.remote_path }}/{{ item.value.file_name }}"
        dest: "{{ osp.resource_path }}/{{ item.value.file_name }}"
      with_dict: "{{ osp.images }}"

    - name: disable NetworkManager and Firewall
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      with_items:
        - NetworkManager
        - firewalld
        
    - name: enable network service
      systemd:
        name: network
        state: started
        enabled: yes
