---
- hosts: osp
  name: Prepare OpenStack Installation

  tasks:
    - name: create resource folder
      file:
        path: "{{ osp.resource_path }}"
        state: directory

    - name: install required packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - centos-release-openstack-queens

    - name: update openstack package
      yum:
        name: '*'
        state: latest
        
    - name: install extra packstack packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - openstack-packstack
        - openstack-utils
        - python-pip

    - name: update packages
      yum:
        name: '*'
        state: latest

    - name: update python pip
      shell: >
        pip install --upgrade pip

    - name: download images
      get_url:
        url: "{{ item.value.remote_path }}/{{ item.value.file_name }}"
        dest: "{{ osp.resource_path }}/{{ item.value.file_name }}"
      with_dict: "{{ osp.images }}"

    - name: disable network manager
      shell: >
        systemctl disable NetworkManager ; systemctl stop NetworkManager ; systemctl enable network ; systemctl start network

    - name: disable firewalld
      systemd:
        name: firewalld
        state: stopped
        enabled: no

    - name: disable selinux
      replace:
        dest: /etc/selinux/config
        regexp: 'SELINUX=enforcing'
        replace: 'SELINUX=disabled'
        backup: no

