---
- import_playbook: servers/undeploy.yml

- hosts: openstack
  name: Deploy Instances for OpenShift Cluster

  tasks:

  - set_fact:
      openshift_domain: example.com
      openstack_public_network_id: $(openstack network show public_network -f value -c id)
      openstack_public_subnet_id: $(openstack subnet show public_subnet -c id -f value)
      openstack_internal_network_id: $(openstack network show lab_network -f value -c id)
      openstack_internal_subnet_id: $(openstack subnet show lab_subnet -c id -f value)
      openstack_default_security_group_id: $(openstack security group list --project lab | grep "Default security group" | cut -d " " -f 2)
      
  - import_tasks: servers/deploy.yml
  - import_tasks: servers/registry-volume.yml
  - import_tasks: servers/wait_for_ssh.yml

- import_playbook: servers/dns/config.yml
- import_playbook: servers/bastion/config.yml
- import_playbook: servers/haproxy/config.yml
- import_playbook: servers/dns/subnet.yml
