all:
  vars:
    ansible_user: centos
    ansible_become: yes

osp:
  hosts:
    openstack:
      ansible_connection: local

lab: 
  hosts:
    ftp:
      ansible_host: 192.168.1.41
    dns:
      ansible_host: 192.168.1.2
    bastion:
      ansible_host: 192.168.1.6
    haproxy:
      ansible_host: 192.168.1.5
