---
- hosts: lab
  name: Configure Servers for Nexus Repository

  tasks:

    - import_tasks: ~/pack-your-lab/nexus/client/configuration.yml

    - name: update packages
      yum:
        name: '*'
        state: latest

    - import_tasks: ~/pack-your-lab/nexus/client/configuration.yml
    
- name: disable firewalld because instances will use security groups rules
  systemd:
    name: firewalld
    state: stopped
    enabled: no       
