---
- hosts: ocp
  name: Prepare System

  tasks:
    - name: Ensure openstack hostname
      shell: hostname {{ inventory_hostname }} && echo "{{ inventory_hostname }}" > /etc/hostname

    - name: Install packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - python2-setuptools
        - wget
        - git
        - net-tools
        - bind-utils
        - iptables-services
        - bridge-utils
        - bash-completion
        - kexec-tools
        - sos
        - psacct
        - atomic-openshift-utils
        - docker-1.13.1
      retries: 10
      delay: 5

    - name: Update packages
      yum:
        name: '*'
        state: latest
      retries: 10
      delay: 5
