---
- hosts: osp
  name: Create DNS Security Group

  tasks:

    - name: create security group / icmp/ssh rules
      shell: >
        source ~/keystonerc_admin && export OS_PROJECT_NAME=lab && \
        security_group_name={{ servers.dns.security_group }} && \
        openstack security group create \
          --description "DNS Security Group" \
          $security_group_name && \
        openstack security group rule create \
          --ingress \
          --protocol icmp \
          $security_group_name && \
        openstack security group rule create \
          --ingress \
          --protocol tcp \
          --dst-port 22 \
          $security_group_name
            
    - name: create rule for port 53 on tcp/udp protocols
      shell: >
        source ~/keystonerc_admin && export OS_PROJECT_NAME=lab && \
        security_group_name={{ servers.dns.security_group }} && \
        openstack security group rule create \
          --ingress \
          --protocol {{ item }} \
          --dst-port 53 \
          $security_group_name
      with_items:
        - udp
        - tcp
